host: "localhost"
database: "test"
user: "admin"
password: "admin"
default-extra-file: "./.db.cnf"

max-connect: 10
max-lifetime-connect-minute: 5
max-lifetime-query-second: 3
log: Yes

filename:
  path: "./target/"
  prefix: "short"
  gzip: Yes
  date-format: "2006-01-02_15:04:05"

tables:
  limit: 100
  full:
    - migration_versions
  ignore:
    - test 
  specs:
    - name: user
      pk:
        - uuid
      fk:
        - col: category_id
          fk_tab: category
          fk_col: id
      sort:
        - updated_at
      limit: 5
      condition: "updated_at > NOW() - INTERVAL 1 WEEK"
