host: "localhost"
database: "test"
user: "admin"
password: "admin"
max-connect: 10
filename:
  path: "./target/"
  prefix: "short"
  gzip: Yes
  date-format: "2006-01-02_15:04:05"

tables:
  limit: 100
  full:
    - migration_versions
  ignore:
    - test 
  specs:
    - name: user
      pk:
        - uuid
      sort:
        - updated_at
      limit: 5
      condition: "updated_at > NOW() - INTERVAL 1 WEEK"
