host: "localhost"
database: "test"
user: "admin"
password: "admin"
filename: "dump_slice.sql"

tables:
  limit: 100
  full:
    - migration_versions
  ignore:
    - test 
  specs:
    - name: user
      pk:
        - uuid
      sort:
        - updated_at
      limit: 5
