version: '3.7'

services:
  mysqldump-slice:
    build:
      context: .
      dockerfile: .build/docker/Dockerfile
    volumes:
      - '.:/app'
    working_dir: /app

networks:
  default:
    name: getic 
    external: true
