version: '3.7'

services:
  mysqldump-slice:
    build:
      context: .
      dockerfile: .build/docker/Dockerfile
    volumes:
      - '.:/app'
      - '${PATH_TO_CONF}:/app/conf.yaml'
    working_dir: /app

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
